spring.profiles.active=wlc
logging.level.com.sintrue=DEBUG
logging.level.wang.liangchen=DEBUG
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=123456
spring.data.redis.database=0