spring:
  datasource:
    url: jdbc:postgresql://10.196.173.197:5432/aps_tst
    username: a_appconnect
    password: NHAp7%N~
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    matrix:
      enabled: true
      datasources:
        ds1:
          url: jdbc:postgresql://10.196.173.197:5432/aps_tst
          username: a_appconnect
          password: NHAp7%N~
          driver-class-name: org.postgresql.Driver
          type: com.zaxxer.hikari.HikariDataSource
        ds2:
          url: jdbc:postgresql://10.196.173.197:5432/aps_tst
          username: a_appconnect
          password: NHAp7%N~
          driver-class-name: org.postgresql.Driver
          type: com.zaxxer.hikari.HikariDataSource
