spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=matrix
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 1000
    matrix:
      datasources:
        sintrue:
          url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sintrue
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            connection-timeout: 2000
        sample:
          url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sample
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            connection-timeout: 3000
