<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>wang.liangchen.matrix</groupId>
        <artifactId>matrix-framework-ddd-example</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </parent>

    <groupId>wang.liangchen.matrix.shop</groupId>
    <artifactId>matrix-shop-product</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>matrix-shop-product-interface</module>
        <module>matrix-shop-product-contract</module>
        <module>matrix-shop-product-client</module>
        <module>matrix-shop-product-application</module>
        <module>matrix-shop-product-domain</module>
        <module>matrix-shop-product-infrastructure</module>
        <module>matrix-shop-product-bootstrap</module>
    </modules>

</project>