<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>wang.liangchen.matrix</groupId>
        <artifactId>matrix-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>matrix-framework-spring</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>matrix-framework-spring-boot</module>
        <module>matrix-framework-spring-web</module>
        <module>matrix-framework-spring-data</module>
        <module>matrix-framework-spring-cloud</module>
        <module>matrix-framework-spring-ai</module>
    </modules>

    <properties>
        <version.spring.boot>3.5.8</version.spring.boot>
        <version.spring.cloud>2025.0.0</version.spring.cloud>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${version.spring.boot}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${version.spring.cloud}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>